## Prova 1 - C210 Lab
-------------------------------------------------------------------------------------------------------------------------------------------------------------
#### Nome: Dimitri Schulz Amado
#### Matrícula: 412

-------------------------------------------------------------------------------------------------------------------------------------------------------------

## Instruções:
- A prova deve ser resolvida em 1h30min.
- A prova é Individual.
- Resolver as questões e enviar as respostas através desse Jupyter Notebook.
- Interpretação faz parte da prova.
- Não será permitida qualquer tipo de consulta, exceto à folha de resumo escrita.
- É proibido portar quaisquer dispositivos eletrônicos de comunicação e de gravação de sons e imagens (aparelho celular, relógios inteligentes – Smartwatch, fones de ouvido, entre outros itens similares), bem como óculos escuros. O aluno que desrespeitar essa determinação terá nota zero e será penalizado de acordo com o Regimento do Inatel.

Boa Prova.

-------------------------------------------------------------------------------------------------------------------------------------------------------------

# (25 Pontos) **`Questão 1`** - Assinale as seguinte afirmações em Verdadeiro (V) ou Falso (F)

**A)** PSO é um algoritmo revolucionário que simula geograficamente o comportamento de espécies. Um exemplo é o nearest neighborn que tem uma lembrança da melhor posição global e individual.          
**R: #** F

-------------------------------------------------------------------------------------------------------------------------------------------------------------

**B)** Heurística é uma função h(n) que estima o custo entre o estado atual e os estados gerados a partir dele.                                        
**R: #** F

-------------------------------------------------------------------------------------------------------------------------------------------------------------

**C)** A* tem como objetivo maximizar o custo de uma busca e utiliza o custo até o objetivo h(n) e o custo de cada nó g(n)                                                                         
**R: #** F

-------------------------------------------------------------------------------------------------------------------------------------------------------------

**D)** Ao contrário do aprendizado supervisionado, onde os dados são rotulados, no clustering, os dados têm rótulos prévios. Isso significa que há uma resposta certa e errada sobre como os dados devem ser agrupados.

**R: #** F

-------------------------------------------------------------------------------------------------------------------------------------------------------------

**E)** Abordagem de busca que não considera nenhuma informação sobre qual sucessor é mais promissor para atingir uma meta (objetivo)                                                                                                                      
**R: #** F

-------------------------------------------------------------------------------------------------------------------------------------------------------------

**Resposta Q1** :
-------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------------

# (30 pontos) **`Questão 2`** -

2.1 (15 Pontos) - Escolha qual deve ser a Queue correta para a Busca em Profundidade - DepthFirstSearch (DFS)
- tire o # da opção escolhida.

2.2 (15 Pontos) - Execute a Busca em Profundidade. E print quantos estados foram visitados.

Estado Inicial

|   0   |   1   |   2   |

|   8   |   4   |   3   |

|   7   |   6   |   5   |

Estado Final

|   1   |   2   |   3   |

|   8   |   0   |   4   |

|   7   |   6   |   5   |


In [4]:
import numpy as np

class SlidingPuzzle():
    def __init__(self, num_blocos):
        '''
        Construtor
        Args:
            - num_blocos: numero de blocos por linha e coluna, valor inteiro (Ex: 3 significa 3 linhas e 3 colunas)
        '''
        self.num_blocos = num_blocos

    def _encontra_posicao(self, estado, elemento):
        '''
        Varre todo o tabuleiro (estado) e verifica em qual posição 'elemento' está
        Args:
            - estado: matriz contendo o estado do tabuleiro
            - elemento: elemento a ser buscado na matriz
        Return:
            - Retorna a linha e coluna onde o elemento se encontra
        '''
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if estado[i, j] == elemento:
                    return i, j
        return None, None

    def verifica_estados(self, atual, objetivo):
        '''
        Verifica se dois estados são iguais
        Args:
            - atual: matriz que descreve o estado atual
            - objetivo: matriz que descreve o estado objetivo
        Return:
            - booleano dizendo se o estado atual é ou não o objetivo
        '''
        flag = True
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if atual[i, j] != objetivo[i, j]:
                    flag = False
                    break

        return flag

    def expande_estados(self, atual):
        '''
        Dado o estado atual, realiza a expansão de estados
        Args:
            - atual: matriz que descreve o estado atual
        Return:
            - lista com os novos estados após a expansão
        '''

        novos_estados = []
        linha, coluna = self._encontra_posicao(atual, 0)

        # Cima
        if linha > 0:
            novo_estado = np.copy(atual)
            nova_linha = linha - 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Baixo
        if linha < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_linha = linha + 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)


        # Esquerda
        if coluna > 0:
            novo_estado = np.copy(atual)
            nova_coluna = coluna - 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Direita
        if coluna < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_coluna = coluna + 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        return novos_estados


In [5]:
from queue import LifoQueue, Queue

class DepthFirstSearch():
    def __init__(self, problema):
        '''
        Construtor
        Args:
            - problema: objeto do problema a ser solucionado
        '''
        self.problema = problema

    def _verifica_visitado(self, estado, estados_visitados):
        '''
        Verifica se 'estado' está na lista de estados visitados
        Args:
            - estado: estado qualquer do tabuleiro
            - estados_visitados: lista com todos os estados já visitados
        Return:
            - booleano dizendo se o estado foi visitado ou não
        '''
        for i in estados_visitados:
            if self.problema.verifica_estados(i, estado):
                return True
        return False

    def busca(self, inicio, fim):
        '''
        Realiza a busca DFS, armazenando os estados em uma PILHA
        Args:
            - inicio: estado inicial do problema
            - fim: estado objetivo
        Return:
            - booleano se a solução foi encontrada, lista dos estados visitados, quantidade de estados visitados
        '''

        # 3.1 Escolha qual deve ser a Queue correta para a Busca em Profundidade - DepthFirstSearch (DFS)
        pilha = LifoQueue()
        #pilha = Queue()

        pilha.put(inicio)

        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0

        while not pilha.empty():
            atual = pilha.get()
            estados_visitados.append(atual)

            if self.problema.verifica_estados(atual, fim):
                solucao_encontrada = True
                print("\n\n")
                print(atual)
                break

            else:
                cont_estados += 1
                print(f"Visitando #{cont_estados}")
                print(atual)
                novos_estados = self.problema.expande_estados(atual)
                for i in novos_estados:
                    if not self._verifica_visitado(i, estados_visitados):
                        pilha.put(i)

        return solucao_encontrada, estados_visitados, cont_estados

2.2 Execute a Busca

In [6]:
# Criando objeto do problema
problema = SlidingPuzzle(3)

# Criando Matriz inicial e matriz alvo
start = np.matrix([[0,1,2],[8,4,3],[7,6,5]])
target = np.matrix([[1,2,3],[8,0,4],[7,6,5]])

# Mostrando informações iniciais
print(f"Initial state: \n{start}")
print("*"*15)
print(f"Target state: \n{target}")
print("*"*15)

Initial state: 
[[0 1 2]
 [8 4 3]
 [7 6 5]]
***************
Target state: 
[[1 2 3]
 [8 0 4]
 [7 6 5]]
***************


In [7]:
# Instancia e executa a busca
busca = DepthFirstSearch(problema)
solucao, visitados, quantidade = busca.busca(start, target)

if solucao:
    print("\nSolução encontrada!")
else:
    print("\nSolução não encontrada!")

Visitando #1
[[0 1 2]
 [8 4 3]
 [7 6 5]]
Visitando #2
[[1 0 2]
 [8 4 3]
 [7 6 5]]
Visitando #3
[[1 2 0]
 [8 4 3]
 [7 6 5]]
Visitando #4
[[1 2 3]
 [8 4 0]
 [7 6 5]]



[[1 2 3]
 [8 0 4]
 [7 6 5]]

Solução encontrada!


# (20 Pontos) **`Questão 3`** -

3.1 (10 Pontos) - Altere o código para que o Crossover ocorra no Terceiro Bit

3.2 (10 Pontos) - Altere o código para que o exista uma probabilidade de 6% de ocorrer mutação.

In [8]:
import numpy as np

# Classe para manutenção de dados no formato de conjunto de bits
class BitSet:

    def __init__(self, size):
        '''
        Construtor
        Args:
            - size: tamanho do bitset
        '''
        # Preencher um array [size] com False
        self.bits = np.full(size, False)

    def __repr__(self):
        '''Definir o que aparecerá quando um objeto for printado'''
        return (f"{self.bits*1}")

    def get(self, index):
        '''
        Retornar o bit da posição 'index'
        Args:
            - index: posição do bit
        '''
        return self.bits[index]

    def set_(self, index, value):
        '''
        Substitui o bit da posição 'index' pelo 'value'
        Args:
            - index: posição a ser substituída
            - value: valor a ser adicionado na posição 'index'
        '''
        self.bits[index] = value

    def flip(self, index):
        '''
        Inverte o bit da posição 'index'
        Args:
            - index: índice do bit a ser invertido
        '''
        self.bits[index] = not self.bits[index]

    def debug(self):
        '''
        Printar os bits
        '''
        print(self.bits)

In [9]:
class Chromossome:

    def __init__(self, x = None, y = None):
        '''
        Construtor
        Atribui o genótipo de x e y ao cromossomo
        Args:
            - x: valor de x
            - y: valor de y
        '''
        x = np.random.randint(-15, 16) if x is None else x
        y = np.random.randint(-15, 16) if y is None else y

        self.genes = Chromossome.get_genotype(x, y)
        self.score = np.inf

    def __repr__(self):
        '''Apresentar os genes e a pontuação quando utilizar print(Chromossome)'''
        return (f'(Gene: {self.genes}, Score: {self.score:.3f})')

    def __lt__(self, other):
        ''' Ordenar em ordem decrescente'''
        return self.score > other.score

    @staticmethod
    def to_binary(variable):
        '''
        Converte o fenótipo (decimal) em genótipo(binário)
        '''
        variable = "{:05b}".format(variable)
        signal = 1 if variable[0] == "-" else 0
        variable = variable[1:]
        variable += str(signal)

        return variable

    @staticmethod
    def get_genotype(x, y):
        '''
        Transforma os fenótipos em genótipos
        '''
        bits = BitSet(10)

        x_genotype = Chromossome.to_binary(x)
        y_genotype = Chromossome.to_binary(y)
        xy_binary = x_genotype + y_genotype

        for i in range(10):
            bits.set_(i, xy_binary[i] == '1')

        return bits

    @staticmethod
    def get_fenotype(genes):
        '''
        Transforma os valores binários dos genes em decimais
        '''
        # XXXXX YYYYY (5 bits to each variable: 4 for value and 1 for sign pos/neg)
        # 01234 56789 (bits are indexed from left to right)
        # 8421K 8421K (bits on indices 4 and 9 represent the variables sign, i.e.
        #              0 represents a positive and 1 represents a negative value)

        x = (8 * genes.get(0) + 4 * genes.get(1) +
             2 * genes.get(2) + 1 * genes.get(3))

        if (genes.get(4) == 1):
            x *= -1

        y = (8 * genes.get(5) + 4 * genes.get(6) +
             2 * genes.get(7) + 1 * genes.get(8))

        if (genes.get(9) == 1):
            y *= -1

        return x, y

In [10]:
class Problem:

    @staticmethod
    def function(x, y):
        '''
        Função avaliada
        '''
        return x**2 + y**2

    @staticmethod
    def score(x, y):
        '''
        Função a ser minimizada
        '''
        return abs(Problem.function(x, y))

    @staticmethod
    def score_chromossome(chromossome):
        '''
        Transforma o genótipo em fenótipo e calcula o valor da função
        '''
        x, y = Chromossome.get_fenotype(chromossome.genes)
        return Problem.score(x, y)

    @staticmethod
    def score_average(population):
        '''
        Pontuação média da população
        '''
        avg = 0
        for chromossome in population:
            avg += Problem.score_chromossome(chromossome)
        avg /= len(population)
        return avg

    @staticmethod
    def update_chromossome_score(chromossome):
        '''
        Atualiza pontuação do cromossomo
        '''
        genes_aux = Chromossome.get_fenotype(chromossome.genes)
        x = genes_aux[0]
        y = genes_aux[1]
        chromossome.score = Problem.score(x,y)

In [11]:
class GeneticUtils:

    @staticmethod
    def find_best_chromossome(population):
        '''
        Retorna o melhor cromossomo
        '''
        population.sort()
        return population[-1]

    @staticmethod
    def find_worst_chromossome(population):
        '''
        Retorna o pior cromossomo
        '''
        population.sort()
        return population[0]

    @staticmethod
    def roulette(population):
        '''
        Retorna probabilidades de cada indivíduo ser selecionado
        '''
        population_scores = [chromossome.score for chromossome in population]
        population_scores = np.array(population_scores)

        # Calculando aptidão
        fitness = 1 / (population_scores + 1)
        total_fitness = fitness.sum()

        roulette_values = fitness / total_fitness
        print(roulette_values)
        return roulette_values

In [12]:
class GeneticOperators:

    @staticmethod
    def selection(population):
        '''
        Seleciona os pais
        '''
        parents = np.random.choice(population, size=2, replace = False)
        parent1, parent2 = parents[0], parents[1]

        return parent1, parent2

    @staticmethod
    def selection_roulette(population):
        '''
        Seleciona os pais baseado em uma probabilidade
        '''
        probabilities = GeneticUtils.roulette(population)
        parents = np.random.choice(population, size=2, replace = False, p = probabilities)
        parent1, parent2 = parents[0], parents[1]

        return parent1, parent2

    @staticmethod
    def crossover(population, parent1, parent2):
        '''
        Aplica o cruzamento
        '''
        crossover_point = 2
        parent1_genes = parent1.genes
        parent2_genes = parent2.genes

        child1_genes = BitSet(10)
        child2_genes = BitSet(10)

        for i in range(crossover_point):
            child1_genes.set_(i, parent1_genes.get(i))
            child2_genes.set_(i, parent2_genes.get(i))

        for i in range(crossover_point, 10):
            child1_genes.set_(i, parent2_genes.get(i))
            child2_genes.set_(i, parent1_genes.get(i))

        child1 = Chromossome()
        child1.genes = child1_genes

        child2 = Chromossome()
        child2.genes = child2_genes

        Problem.update_chromossome_score(child1)
        Problem.update_chromossome_score(child2)

        print("========= CROSSOVER ==========")
        print(f"PARENTS:\n{parent1}\n{parent2}")
        print(f"CHILDREN:\n{child1}\n{child2}")
        print("==============================")

        population.append(child1)
        population.append(child2)

    @staticmethod
    def mutation(population, mutation_threshold):
        '''
        Aplica a mutação
        '''
        prob = np.random.uniform(0, 1)

        if prob >= mutation_threshold:
            return

        chromossome = np.random.choice(population)
        print("========== MUTATING ==========")
        print(chromossome)

        mutation_point = np.random.randint(0, 10)
        chromossome.genes.flip(mutation_point)
        Problem.update_chromossome_score(chromossome)
        print(chromossome)
        print("==============================")

    @staticmethod
    def elitism(population):
        '''
        Remove o pior indivíduo
        '''
        print("========== REMOVING ==========")
        for _ in range(2):
            worst_individual = GeneticUtils.find_worst_chromossome(population)
            print(worst_individual)
            population.remove(worst_individual)

In [13]:
MAX_GENERATION = 100
INITIAL_POPULATION = 100
MUTATION_THRESHOLD = 0.06

if __name__ == "__main__":

    # População inicial
    population = []
    for _ in range(INITIAL_POPULATION):
        chromossome_aux = Chromossome()
        Problem.update_chromossome_score(chromossome_aux)
        population.append(chromossome_aux)

    # Variáveis de controle
    generation = 0
    population_score = []

    # Para cada geração
    while generation < MAX_GENERATION:
        print(f"GENERATION: {generation}")
        print(f"POPULATION:\n{population}")
        # Pontuação da população
        population_score.append(Problem.score_average(population))

        # Seleção
        parent1, parent2 = GeneticOperators.selection_roulette(population)

        # Crossover
        GeneticOperators.crossover(population, parent1, parent2)

        # Mutação
        GeneticOperators.mutation(population, MUTATION_THRESHOLD)

        # Elitismo
        GeneticOperators.elitism(population)

        print(f"Average score: {population_score[generation]}")
        print("="*50)

        generation += 1

    best_chromossome = GeneticUtils.find_best_chromossome(population)
    print(f"Best chromossome {best_chromossome}")

GENERATION: 0
POPULATION:
[(Gene: [0 1 1 0 1 1 1 0 0 1], Score: 180.000), (Gene: [0 1 0 1 0 1 1 1 0 0], Score: 221.000), (Gene: [0 1 0 1 1 1 0 0 0 1], Score: 89.000), (Gene: [0 1 0 0 1 0 1 1 1 1], Score: 65.000), (Gene: [1 0 1 0 0 1 1 1 1 0], Score: 325.000), (Gene: [0 1 1 0 1 1 0 0 1 1], Score: 117.000), (Gene: [0 0 1 1 0 1 1 0 1 0], Score: 178.000), (Gene: [0 0 1 0 0 0 1 0 0 0], Score: 20.000), (Gene: [1 1 1 1 1 0 0 0 0 0], Score: 225.000), (Gene: [0 0 0 0 0 0 0 1 1 0], Score: 9.000), (Gene: [0 0 0 0 0 1 1 0 0 0], Score: 144.000), (Gene: [0 0 1 0 1 0 1 1 1 1], Score: 53.000), (Gene: [0 1 1 1 1 1 1 1 1 1], Score: 274.000), (Gene: [1 0 1 1 0 0 1 1 0 0], Score: 157.000), (Gene: [0 0 1 0 0 0 0 1 0 1], Score: 8.000), (Gene: [0 1 0 1 1 1 0 1 0 1], Score: 125.000), (Gene: [1 0 0 1 1 1 0 1 0 0], Score: 181.000), (Gene: [0 1 1 0 0 0 0 1 0 1], Score: 40.000), (Gene: [0 0 0 1 1 1 0 1 0 1], Score: 101.000), (Gene: [1 0 1 1 1 1 1 0 0 1], Score: 265.000), (Gene: [1 1 1 0 0 0 0 0 1 0], Score: 197.0

# (25 Pontos) **`Questão 4`** - Regressão com Random Forest

Você recebeu um conjunto de dados meteorológicos chamado weatherHistory.csv, contendo registros históricos do clima. Entre as colunas disponíveis estão:

    Temperature (C) — temperatura registrada em graus Celsius (alvo da previsão)

    Humidity — umidade relativa do ar

    Wind Speed (km/h) — velocidade do vento em km/h

    Visibility (km) — visibilidade em quilômetros

    Pressure (millibars) — pressão atmosférica

    Apparent Temperature (C) — sensação térmica em graus Celsius

    Summary, Precip Type, Daily Summary — variáveis categóricas (não utilize nesta questão)

Seu objetivo é treinar um modelo de regressão utilizando o algoritmo Random Forest Regressor, a fim de prever a variável Temperature (C) com base nas demais variáveis numéricas

4.1 (5 Pontos) - Carregue o dataset usando pandas e exiba as 5 primeiras linhas.

4.2 (5 Pontos) - Separe os dados em variáveis de entrada (X) e saída (y).

4.3 (5 pontos) - Divida os dados em um conjunto de treino e outro de teste, com a proporção de 80% e 20% respectivamente.

4.4 (5 Pontos) - Treine um modelo de Random Forest.

4.5 (5 Pontos) - Avalia o modelo com a métrica R² Score no conjunto de teste.

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [17]:
df = pd.read_csv('weatherHistory.csv')
df.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0          15.8263         0.0               1015.63   
2                   204.0          14.9569         0.0               1015.94   
3                   269.0          15.8263         0.0               1016.41   
4                   259.0          15.8263         0.0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [ ]:
X = df[['Temperature (C)', 'Humidity', 'Wind Speed (km/h)']]
y = df['Apparent Temperature (C)']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestRegressor(n_estimators=100, random_state=42)

In [21]:
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [23]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print(f"R² Score: {r2:.3f}")

R² Score: 1.000
